
################################################################################
# Generated by gaic v1.3 on 2024:03:26 20:26
# Do NOT edit or it might get overwritten. Please edit the .gcloudconfig.yaml (and if needed relaunch the script)!
################################################################################

# require_relative './_env_gaic.rb' 
ENV["PROJECT_ID"] = "ric-cccwiki"
ENV["PROJECT_NUMBER"] = "134140879415"
ENV["GCP_REGION"] = "us-central1"
ENV["GCP_ZONE"] = "us-central1-b"
ENV["GCP_ACCOUNT"] = "palladiusbonton@gmail.com"
ENV["BUCKET"] = "gs://ric-cccwiki-bucket"
