
################################################################################
# Generated by gaic v1.3 on 2024:04:14 22:49
# Do NOT edit or it might get overwritten. Please edit the .gcloudconfig.yaml (and if needed relaunch the script)!
################################################################################

# require_relative './_env_gaic.rb' 
ENV["PROJECT_ID"] = "ric-cccwiki"
ENV["PROJECT_NUMBER"] = "134140879415"
ENV["GCP_REGION"] = "us-central1"
ENV["GCP_ZONE"] = "us-central1-b"
ENV["GCP_ACCOUNT"] = "palladiusbonton@gmail.com"
ENV["DESCRIPTION"] = "This is my personal account - doing things like everyone else to test no whitelisting.
I also have my geminisse SA just created and deployed for ricc. Also added the expiry date."
ENV["KEY_EXPIRY_DATE"] = "2024-07-09"
ENV["STD_SA_LOCATION"] = "private/ric-cccwiki.json"
ENV["BUCKET"] = "gs://ric-cccwiki-bucket"
