
################################################################################
# Generated by gaic v1.3 on 2024:04:09 05:22
# Do NOT edit or it might get overwritten. Please edit the .gcloudconfig.yaml (and if needed relaunch the script)!
################################################################################

# require_relative './_env_gaic.rb' 
ENV["PROJECT_ID"] = "ric-cccwiki"
ENV["GCP_REGION"] = "us-central1"
ENV["GCP_ZONE"] = "us-central1-b"
ENV["GCP_ACCOUNT"] = "palladiusbonton@gmail.com"
ENV["description"] = "This is my personal account - doing things like everyone else
to test no whitelisting.
"
ENV["BUCKET"] = "gs://ric-cccwiki-bucket"
