
list:
    just -l

run:
  bin/dev

run-prod:
  echo first time: DISABLE_DATABASE_ENVIRONMENT_CHECK=1 RAILS_ENV=production rails db:drop db:setup db:migrate db:seed
  RAILS_ENV=production rails s -p 8080

recreate-db:
    rails db:drop db:setup db:migrate db:seed

# echo  🏗️ scaffolding:
#bin/rails generate scaffold_controller Chats model_id:string user:references title:string summary:text

dev-removeme-test-adding-a-question:
  echo " puts(GEMINI_API_KEY) ; c = Chat.find 5 ; c.ask 'Quali sono le principali citta italiane, per popolazione?'" | rails c


# c.with_instructions 'You only speak french and use emoji for anything'
