
set export

# Should get them from envrc...
export PROJECT_ID := 'g25-games'
#GCP_REGION := 'fake-antarctica-east-1'

# Lists all targets
[group('default')]
list:
    @yellow "[justfile] PROJECT_ID=$PROJECT_ID"
    @just -l


# Creates '.firebase.rc' with proper project_id
init:
    if [ -f .firebaserc ] ; then echo inutile ; exit 2 ; fi
    firebase init
    firebase init hosting --project $PROJECT_ID --add

# .firebase.rc

deploy:
    echo on derek: node_modules/.bin/firebase deploy
    firebase deploy

push: deploy

emulate:
  firebase emulators:start
