# this justfile was created by carlessize-folder v#{VERSION} on #{Time.now}
#source .envrc  # Loads your environment variables
#set SPANNOMETRIC_VERSION := 3
set export

# Should get them from envrc...
PROJECT_ID := "justfile_pincopallo"
GCP_REGION := 'justfile-antarctica-east-1'


# Lists all targets
[group('default')]
list:
    @yellow "[justfile] PROJECT_ID=$PROJECT_ID"
    @yellow "[justfile] GCP_REGION=$GCP_REGION"
    @just -l # | lolcat

# 1. Send a request to the model
test1:
    uv run python test1.py


clone-repo:
    git clone https://github.com/google/computer-use-preview
