# on derek
install-linux:
    sudo apt install npm
    # togli g se non funge
    npm install -g firebase-tools

#    npm install -g firebase-tools
install-mac:
    npm install firebase-tools
# se no trova usa ./node_modules/.bin/firebase

login:
    echo 'se non va fai cosi: export PATH=$PATH:node_modules/.bin/firebase'
    firebase init
    firebase login

deploy:
    echo on derek: node_modules/.bin/firebase deploy
    firebase deploy

