# frozen_string_literal: true

#################################################
# Riccardo readmes:
# * https://kolosek.com/rails-bundle-install-and-gemfile/
# * https://github.com/googleapis/google-auth-library-ruby
# * PR 513: https://github.com/patterns-ai-core/langchainrb/pull/513/files#diff-86baf19d3db04ca4b773792c27230e17bb4ba4f9373d17688b8a2f67de6f9c28
#################################################

source 'https://rubygems.org'

gem 'dotenv'
gem 'google-apis-aiplatform_v1', "~> 0.8"
#gem 'google_palm_api'

# Experimental from Andrei with Gemini and News reading support!
# Download a new one: $GICBIN/download-andrei-pr513.sh
#gem "langchainrb", path: '../../langchainrb-pr513-v3/'
gem "langchainrb", '~> 0.13.1' # , path: '../../langchainrb-pr513-v3/'
#gem 'httparty'

# gem 'langchainrb',
#   :git => '~/git/langchainrb-pr513/',
#   :branch => ' google-gemini-assistant-support'
#gem 'googleauth' # https://github.com/googleapis/google-auth-library-ruby
#gem 'googleauth', '~> 0.4.1' # But hey, latest is 1.11.0!!
gem 'googleauth', '~> 1.11.0' # But hey, latest is 1.11.0!!
#gem 'googleauth', '~> 0.7' # But hey, latest is 1.11.0!!
gem 'lolcat'
gem 'json', '~> 2.7', '>= 2.7.2'

# gem 'pragmatic_segmenter', '0.3.23'
# gem 'unicode', '~> 0.3'

# For tools
gem 'google_search_results'
gem "wikipedia-client", "~> 1.17.0"
gem 'faraday' # for ollama
#gem 'httparty' # for function calling
#gem 'httparty' # , '~> 0.13.7' # or gives me this error: undefined DIG methos: https://gitlab.com/gitlab-org/gitlab-foss/-/issues/60827
gem 'httparty', '0.21.0'

gem "ruby-openai", "~> 6.3.0" # for OpenAI
gem 'google-cloud-storage'
# gbaptista again! :)
#gem 'ollama-ai', '~> 1.2.1'
