# frozen_string_literal: true

source 'https://rubygems.org'

#gem 'dotenv'
gem 'google-apis-aiplatform_v1'
# gem 'google_palm_api'
# Experimental from Andrei with Gemini and News reading support!
#gem 'langchainrb', '~> 0.12.0'
#gem "langchainrb", path: "~/git/langchainrb-pr513/"

# bundle config local.langchainrb ~/git/langchainrb-pr513/


# gem 'langchainrb', :github => 'rack/langchainrb', :branch => 'google-gemini-assistant-support'
#gem 'langchainrb', :git => File.expand_path("~/git/langchainrb-pr513/"), :branch => 'google-gemini-assistant-support'

# gem 'google-apis-aiplatform_v2'

#gem 'nice_hash'

# gem 'dotenv-rails', groups: [:development, :test]


# Trying https://github.com/gbaptista/gemini-ai
# gem 'gemini-ai', '~> 3.2.0' # requires ruby 3.1
# gem 'colorize'
# gem 'mimemagic' # for autodetect of images and videos
# gem "rubocop-rails-omakase", require: false, group: [ :development ]
