
test1:
	bundle exec ruby 202405-testing-functions.rb

test2:
	bundle exec ruby news_api_test.rb

test-wikipedia-and-gemma:
	./langchainrb-crawl-page.rb Donald Trump
	./langchainrb-crawl-page.rb Silvio Berlusconi

auth:
	gcloud todo
