# This is a sample from version v1.0
# Code: https://github.com/palladius/sakura/blob/master/bin/auto_import_config.py
#
#
# Note: this is PUBLIC
#
local_config:
  auto: true
configurations:
  # # Note: gcloud wont accept this config name if it starts with a number (#btdt)
  gemma-is-born:
    project: clouddeploy-vertexai-demovegas
    compute/region: us-central1
    compute/zone: us-central1-b
    account: palladiusbonton@gmail.com
