
test1:
	./gemma-hello.sh

test2:
#	./gemma-ask.sh 'I have a wife and two boys and we live with my mum, Lucilla. Am I married? How big is my family? How many males? Make sure to include me (a male) in the answer. Answer in JSON'
	./gemma-ask.sh 'I bouth a box of 12 chocolates and my kids ate 2 of them each. How many chocolates are left? Answer in JSON'
