
clean:
	rm output/*.png output/*.JPG output/t.base64


generate4riccardo:
	PROJECT_ID=ricc-genai FILENAME='santaklaus-ironman-fi' ./images-generate.sh Santa Klaus is a triathlete, on Santa Klaus chest you can read: Ironman Finland

generate-pizza:
	PROJECT_ID=ricc-genai FILENAME='pizza-pineapple' ./images-generate.sh "A handsome and sad Italian chef shows a pizza with pineapple"

generate-chair:
	PROJECT_ID=ricc-genai FILENAME='purple-chair' ./images-generate.sh  'magazine style, 4k, photorealistic, modern purple armchair, natural lighting. Sitting on the chair, a person wearing glasses'
