
clean:
	rm output/*.png output/*.JPG output/t.base64


generate4riccardo:
	PROJECT_ID=ricc-genai FILENAME='santaklaus-ironman-fi' ./images-generate.sh Santa Klaus is a triathlete, on Santa Klaus chest you can read: Ironman Finland
#	PROJECT_ID=ricc-genai FILENAME='pizza-pineapple' ./images-generate.sh A pizza with pineapple cooked by a tormented Italian chef
