
clean:
	rm output/*.png output/*.JPG output/t.base64


generate4riccardo:
	PROJECT_ID=ricc-genai FILENAME='santaklaus-ironman-fi' ./images-generate.sh Santa Klaus is a triathlete, on Santa Klaus chest you can read: Ironman Finland

generate-pizza:
	PROJECT_ID=ricc-genai FILENAME='pizza-pineapple' ./images-generate.sh "A handsome and sad Italian chef shows a pizza with pineapple"

generate-chair:
	PROJECT_ID=ricc-genai FILENAME='purple-chair' ./images-generate.sh  'magazine style, 4k, photorealistic, modern purple armchair, natural lighting. Sitting on the chair, a person wearing glasses'

generate-ale:
	PROJECT_ID=ricc-genai FILENAME='aj-stuff' ./images-generate.sh  'A dragon is spitting fire, over a big treasure full of precious stones.'
generate-seby:
	PROJECT_ID=ricc-genai FILENAME='sl-stuff' ./images-generate.sh  'A giraffe dressed like a firefighter is helping putting off a fire in a city populated by giraffes'

generate-child:
# This is likwely going to hit errors and produce nothing.
	PROJECT_ID=ricc-genai FILENAME='child' ./images-generate.sh  'A blonde smiling green-eyed 6-year-old child playing with Pokemon cards'
