

.venv:
	python3 -m venv .venv
	echo Riccardo now do: . .venv/bin/activate

install: .venv
	pip install -r requirements.txt

run-01-quickstart:
	mesop 01-mesop-quickstart.py


run-02-duochat:
	mesop 02-duochat.py
