# this justfile was created by $0 on $(data)
#source .envrc  # Loads your environment variables
#set shell := ["powershell.exe", "-c"]
#set SPANNOMETRIC_VERSION := 3
set export

# Should get them from envrc...
#PROJECT_ID := "justfile_pincopallo"
#GCP_REGION := 'justfile-antarctica-east-1'

# Lists all targets
[group('default')]
list:
    # @yellow "[justfile] PROJECT_ID=$PROJECT_ID"
    # @yellow "[justfile] GCP_REGION=$GCP_REGION"
    # @yellow "[justfile] PROJECT_DESCRIPTION=$PROJECT_DESCRIPTION"
    # @yellow "[justfile] DOCKER_IMAGE=$DOCKER_IMAGE"
    @just -l # | lolcat

# Explains how this script was created.
[group('default')]
explain:
	@green 'This was created by $0 on $(date)'

# Takes sample email (sample.eml) and calls americanize
[group('americanize')]
americanize-sample-email:
  cat sample.eml | ./llm-americanize.py
