PROJECT_ID := 'gugley-3d-tetris'
default: list

# on derek
install-linux:
    sudo apt install npm
    # togli g se non funge
    npm install -g firebase-tools

list:
    just -l

#    npm install -g firebase-tools
install-mac:
    npm install firebase-tools
# se no trova usa ./node_modules/.bin/firebase

login:
    echo 'se non va fai cosi: export PATH=$PATH:node_modules/.bin/firebase'
    firebase init
    firebase login

# Creates '.firebase.rc' with proper project_id
init:
    if [ -f .firebaserc ] ; then echo inutile ; exit 2 ; fi
    firebase init

# .firebase.rc

deploy:
    echo on derek: node_modules/.bin/firebase deploy
    firebase deploy

push: deploy
