
# Change to your project id.
export PROJECT_ID := 'zurigram'
# Needed if firebase script is installed in local folder and not globally.
PATH := "$PATH:node_modules/.bin/firebase"

default: list


# on derek
install-linux:
    sudo apt install npm
    npm install -g firebase-tools || npm install firebase-tools
    echo All good

list:
    just -l
    echo "PATH=$PATH"

#    npm install -g firebase-tools
install-mac:
    npm install firebase-tools
# se no trova usa ./node_modules/.bin/firebase

login:
    echo 'se non va fai cosi: export PATH=$PATH:node_modules/.bin/firebase'
    firebase init
    firebase login

# Creates '.firebase.rc' with proper project_id
init:
    if [ -f .firebaserc ] ; then echo inutile ; exit 2 ; fi
    firebase init

# .firebase.rc

deploy:
    echo on derek: node_modules/.bin/firebase deploy
    firebase deploy

# Magically open app on browser
open:
    open "https://$PROJECT_ID.web.app"

push: deploy
